services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/code
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    networks:
      - backend
    environment:
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      DEBUG: "True"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: bookstore_db
      SQL_USER: bookstore_dev
      SQL_PASSWORD: bookstore_dev
      SQL_HOST: db
      SQL_PORT: 5432
      SECRET_KEY: "key"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
networks:
  backend:
    driver: bridge
volumes:
  app_data:
  postgres_data:
