# Generated by Django 5.2.3 on 2025-07-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='activate',
            new_name='active',
        ),
    ]
